Gambling_Proj/Controllers/TblRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gambling_Proj.Models;

namespace Gambling_Proj.Controllers
{
    public class TblRolesController : Controller
    {
       
        Gambling_AppContext db = new Gambling_AppContext();
        
        // GET: TblRoles
        public IActionResult Index()
        {
            return View(db.TblRole.ToList());
        }

        // GET: TblRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblRole = await db.TblRole
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (tblRole == null)
            {
                return NotFound();
            }

            return View(tblRole);
        }

        // GET: TblRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TblRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,Role,Active,Discription,CreatedBy,CreatedDate")] TblRole tblRole)
        {
            if (ModelState.IsValid)
            {
                db.Add(tblRole);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblRole);
        }

        // GET: TblRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblRole = await db.TblRole.FindAsync(id);
            if (tblRole == null)
            {
                return NotFound();
            }
            return View(tblRole);
        }

        // POST: TblRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,Role,Active,Discription,CreatedBy,CreatedDate")] TblRole tblRole)
        {
            if (id != tblRole.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(tblRole);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblRoleExists(tblRole.RoleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblRole);
        }

        // GET: TblRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblRole = await db.TblRole
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (tblRole == null)
            {
                return NotFound();
            }

            return View(tblRole);
        }

        // POST: TblRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblRole = await db.TblRole.FindAsync(id);
            db.TblRole.Remove(tblRole);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblRoleExists(int id)
        {
            return db.TblRole.Any(e => e.RoleId == id);
        }
    }
}

Gambling_Proj/Controllers/TblUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Gambling_Proj.Models;
using Microsoft.AspNetCore.Http;

namespace Gambling_Proj.Controllers
{
    public class TblUsersController : Controller
    {
        //private readonly Gambling_AppContext _context;
        Gambling_AppContext db = new Gambling_AppContext();

      //  public TblUsersController(Gambling_AppContext context)
        //{
       //     _context = context;
       // }

        public IActionResult Index()
        {

            var user = HttpContext.Session.GetString("Username");
            ViewBag.UserName = user;
            return View(db.TblUser.ToList());
        }
        // GET: TblUsers
      //  public async Task<IActionResult> Index()
      //  {
       //     return View(await db.TblUser.ToListAsync());
      //  }

        // GET: TblUsers/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblUser = await db.TblUser
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (tblUser == null)
            {
                return NotFound();
            }

            return View(tblUser);
        }

        // GET: TblUsers/Create
      //  public IActionResult CreatePartial()
      //  {
      //      return View();
      //  }

        // POST: TblUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Username,Password,Lock,RoleId,CreatedBy,CreatedDate")] TblUser tblUser)
        {
            if (ModelState.IsValid)
            {
                db.Add(tblUser);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblUser);
        }

        // GET: TblUsers/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblUser = await db.TblUser.FindAsync(id);
            if (tblUser == null)
            {
                return NotFound();
            }
            return View(tblUser);
        }

        // POST: TblUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("UserId,Username,Password,Lock,RoleId,CreatedBy,CreatedDate")] TblUser tblUser)
        {
            if (id != tblUser.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(tblUser);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblUserExists(tblUser.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblUser);
        }

        // GET: TblUsers/Delete/5
        public async Task<IActionResult> Delete(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblUser = await db.TblUser
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (tblUser == null)
            {
                return NotFound();
            }

            return View(tblUser);
        }

        // POST: TblUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(decimal id)
        {
            var tblUser = await db.TblUser.FindAsync(id);
            db.TblUser.Remove(tblUser);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblUserExists(decimal id)
        {
            return db.TblUser.Any(e => e.UserId == id);
        }
    }
}

Gambling_Proj/Controllers/UsersGamRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Gambling_Proj.Controllers
{
    public class UsersGamRController : Controller
    {
        // GET: UsersGamRController
        public IActionResult Index()
        {

            return View();
        }

        // GET: UsersGamRController/Details/5
        public IActionResult View(int id)
        {
            return View();
        }

        // GET: UsersGamRController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersGamRController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersGamRController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UsersGamRController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersGamRController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UsersGamRController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Gambling_Proj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/dist/css/styles.css" rel="stylesheet" />

    <style>
        .navbar {
            background-color: #560505;
        }

        .navbar-brand {
            color: yellow;
        }

            .navbar-brand:hover {
                color: #ffd800;
            }

        #sidebarToggle {
            color: #ffffff;
        }

        .fa-bars {
            color: #ffffff;
        }

        .img-user {
            border-radius: 50%;
            height: 100px;
            width: 100px;
        }

        .nav-link {
            background-color: #560505;
            color: #fff;
        }

        .sb-sidenav-menu {
            background-color: #560505;
            color: #fff;
        }

        .sb-sidenav-dark .sb-sidenav-menu .nav-link {
            color: #fff;
        }

        .fass {
            color: #fff;
        }

        #userDropdown:hover {
            color: #fff;
        }

        h1 {
            margin-top: 0.5rem !important;
            font-size: 1.5rem;
        }
    </style>
</head>
<body class="sb-nav-fixed nav_bar">
    <nav class="sb-topnav navbar navbar-expand">
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <a class="navbar-brand" href="index.html">Application Name</a>

        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">

                <div class="input-group-append">

                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">

                        <div class="" style="padding-left: 50px;background-color: #670c0c;">
                            <img src="~/Login/images/user.jpg" class="img-user"><br />
                            <p style="margin-bottom:0rem;">Aung Moe Htin</p>
                            <p style="padding-left: 30px;">master</p>
                        </div>


                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open fass"></i></div>
                            Setups
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down fass"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" asp-controller="TblUsers" asp-action="Index">
                                    Users
                                   </a>
                                <!--<div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Item</a>
                                        <a class="nav-link" href="register.html">Item</a>
                                        <a class="nav-link" href="password.html">item</a>
                                    </nav>
                                </div>-->
                                <a class="nav-link collapsed" asp-controller="TblRoles" asp-action="Index">
                                    User Roles
                                </a>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Football Teams
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Commision
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Unit/Point
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseSetting" aria-expanded="false" aria-controls="collapseSetting">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open fass"></i></div>
                            Settings
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down fass"></i></div>
                        </a>
                        <div class="collapse" id="collapseSetting" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapse_sub" aria-expanded="false" aria-controls="pagesCollapse_sub">
                                    History Clean Setting
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <!--<div class="collapse" id="pagesCollapse_sub" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Item1</a>
                                        <a class="nav-link" href="register.html">Item2</a>
                                        <a class="nav-link" href="password.html">item3</a>
                                    </nav>
                                </div>-->
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapse_Sub2" aria-expanded="false" aria-controls="pagesCollapse_Sub2">
                                    Gambling Teams Setting
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapse_Sub2" aria-expanded="false" aria-controls="pagesCollapse_Sub2">
                                    Gambling Account Setting
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapse_Sub2" aria-expanded="false" aria-controls="pagesCollapse_Sub2">
                                    Role Permission
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                            </nav>
                        </div>


                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns fass"></i></div>
                            Reports
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down fass"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="UsersGamR" asp-action="Index">Users Gambling Report</a>
                                <a class="nav-link" href="#">Win Report</a>
                                <a class="nav-link" href="#">Win Report</a>
                                <a class="nav-link" href="#">Users Report</a>
                                <a class="nav-link" href="#">Activity Log</a>
                            </nav>
                        </div>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table fass"></i></div>
                            LOGOUT
                        </a>
                    </div>
                </div>
                <!--<div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>-->
            </nav>
        </div>
        <div id="layoutSidenav_content">
           
            <main>

                <div class="container-fluid">

                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>

                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/assets/demo/datatables-demo.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/assets/demo/datatables-demo.js"></script>
    <script src="~/dist/js/scripts.js"></script>


    @RenderSection("Scripts", required: false)

</body>
</html>